import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";

import "./globals.css";
import "./prosemirror.css";
import { Toaster } from "sonner";
import { TanstackProvider } from "@/providers";
import NextTopLoader from "nextjs-toploader";

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dmSans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Black Diamond Foundation",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} bg-[#111111]`}>
        <NextTopLoader showSpinner={false} color="white" />
        <TanstackProvider>{children}</TanstackProvider>
        <Toaster />
      </body>
    </html>
  );
}
